Shop/Shop/Models/Kindergarden/KinderGardenCreateUpdateViewModel.cs
using Shop.Models.Realestate;

namespace Shop.Models.Kindergarden
{
    public class KinderGardenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergardenName { get; set; }

        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Shop/Shop/Models/Kindergarden/KinderGardenDeleteViewModel.cs
namespace Shop.Models.Kindergarden
{
    public class KinderGardenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergardenName { get; set; }

        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Shop/Shop/Models/Kindergarden/KinderGardenDetailsViewModel.cs
namespace Shop.Models.Kindergarden
{
    public class KinderGardenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergardenName { get; set; }

        public string Teacher { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Shop/Shop/Models/Kindergarden/KinderGardenViewModel.cs
namespace Shop.Models.Kindergarden
{
    public class KinderGardenViewModel
    {
        public Guid? Id { get; set; }
        public string GroupName { get; set; }
        public int ChildrenCount { get; set; }
        public string KindergardenName { get; set; }

        public string Teacher { get; set; }
    }
}

Shop/Shop/Controllers/KindergardenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.ApplicationServices.Services;
using Shop.Core.Dto;
using Shop.Core.ServiceInterface;
using Shop.Data;
using Shop.Models.Kindergarden;
using Shop.Models.Realestate;
using Shop.Models.Spaceship;

namespace Shop.Controllers
{
    public class KindergardenController : Controller
    {
        private readonly ShopContext _context;
        private readonly IKinderGardenServices _kindergardenService;
        // GET: KindergardenController
        public KindergardenController
           (
           ShopContext context,

           IKinderGardenServices kindergardenService
           )
        {
            _context = context;

            _kindergardenService = kindergardenService;
        }


        public IActionResult Index()
        {
            var result = _context.Kindergardens
                .Select(x => new KinderGardenViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    ChildrenCount = x.ChildrenCount,
                    KindergardenName = x.KindergardenName,
                    Teacher = x.Teacher,
                });

            return View(result);
        }


        [HttpGet]
        public IActionResult Create()
        {
            KinderGardenCreateUpdateViewModel kindergarden = new KinderGardenCreateUpdateViewModel();

            return View("CreateUpdate", kindergarden);
        }


        [HttpPost]
        public async Task<IActionResult> Create(KinderGardenCreateUpdateViewModel vm)
        {
            var dto = new KinderGardenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergardenName = vm.KindergardenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
            };

            var result = await _kindergardenService.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Index), vm);
            //return index

        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarden = await _kindergardenService.GetAsync(id);

            if (kindergarden == null)
            {
                return NotFound();

            }
            var vm = new KinderGardenDetailsViewModel();

            vm.Id = kindergarden.Id;
            vm.GroupName = kindergarden.GroupName;
            vm.ChildrenCount = kindergarden.ChildrenCount;

            vm.KindergardenName = kindergarden.KindergardenName;

            vm.Teacher = kindergarden.Teacher;

            vm.CreatedAt = kindergarden.CreatedAt;
            vm.UpdatedAt = kindergarden.UpdatedAt;




            return View(vm);



        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarden = await _kindergardenService.GetAsync(id);

            if (kindergarden == null)
            {
                return NotFound();
            }


            var vm = new KinderGardenCreateUpdateViewModel();

            vm.Id = kindergarden.Id;
            vm.GroupName = kindergarden.GroupName;
            vm.ChildrenCount = kindergarden.ChildrenCount;

            vm.KindergardenName = kindergarden.KindergardenName;

            vm.Teacher = kindergarden.Teacher;

            vm.CreatedAt = kindergarden.CreatedAt;
            vm.UpdatedAt = kindergarden.UpdatedAt;

            return View("CreateUpdate", vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(KinderGardenCreateUpdateViewModel vm)
        {
            var dto = new KinderGardenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergardenName = vm.KindergardenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = DateTime.Now,
            };
            var result = await _kindergardenService.Update(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index), vm);

            }
            return RedirectToAction(nameof(Index), vm);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarden = await _kindergardenService.GetAsync(id);
            if (kindergarden == null)
            {
                return NotFound();
            }
            var vm = new KinderGardenDeleteViewModel();

            vm.Id = kindergarden.Id;
            vm.GroupName = kindergarden.GroupName;
            vm.ChildrenCount = kindergarden.ChildrenCount;

            vm.KindergardenName = kindergarden.KindergardenName;

            vm.Teacher = kindergarden.Teacher;
            vm.CreatedAt = kindergarden.CreatedAt;
            vm.UpdatedAt = kindergarden.UpdatedAt;

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var kindergardenId = await _kindergardenService.Delete(id);

            if (kindergardenId == null)
            {
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Shop/Views/Kindergarden/CreateUpdate.cshtml
@model Shop.Models.Kindergarden.KinderGardenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>

}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />


        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="KindergardenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="KindergardenName" class="form-control" />

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />

            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="CreatedAt" class="form-control" />

            </div>
        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="UpdatedAt" class="form-control" />

            </div>
        </div>
        <hr />
        @if (Model.Id.HasValue)
        {
            <input asp-action="Update" asp-controller="Kindergarden" type="submit" class="btn btn-primary" value="Update" />

        }
        else
        {
            <input asp-action="Create" asp-controller="Kindergarden" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>
    </form>
</div>

Shop/Shop/Views/Kindergarden/Delete.cshtml
@model Shop.Models.Kindergarden.KinderGardenDeleteViewModel

<h1>Delete</h1>


<duv>

    <h4>Kindergarden</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.Id)

        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.GroupName)

        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.ChildrenCount)

        </div>

        <div class="form-group row">
            <label asp-for="KindergardenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.KindergardenName)

        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.Teacher)

        </div>
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.CreatedAt)

        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.UpdatedAt)

        </div>

    </dl>
    </hr>
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="index" class="btn btn-pimary">Index</a>
    </form>


</duv>

Shop/Shop/Views/Kindergarden/Details.cshtml
@model Shop.Models.Kindergarden.KinderGardenDetailsViewModel

<h1>Delete</h1>


<div>

    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.Id)

        </div>

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.GroupName)

        </div>

        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.ChildrenCount)

        </div>

        <div class="form-group row">
            <label asp-for="KindergardenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.KindergardenName)

        </div>

        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.Teacher)

        </div>
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.CreatedAt)

        </div>

        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model=>Model.UpdatedAt)

        </div>

    </dl>
    </hr>
    <a asp-action="index" class="btn btn-primary">Back</a>
</div>

Shop/Shop/Views/Kindergarden/Index.cshtml
@model IEnumerable<Shop.Models.Kindergarden.KinderGardenViewModel>



@{
    int rowNumber = 1;
}

<div>
    <a asp-action="Create" asp-controller="KinderGarden" class="btn btn-primary">Create</a>
</div>




<form method="post">
    <table class=" table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">GroupName</th>
                <th scope="col">ChildrenCount</th>
                <th scope="col">KindergardenName</th>
                <th scope="col">Teacher</th>




                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kindergarden in Model)
            {
                <tr>
                    <td>@rowNumber</td>

                    <td>@kindergarden.GroupName</td>
                    <td>@kindergarden.ChildrenCount</td>
                    <td>@kindergarden.KindergardenName</td>
                    <td>@kindergarden.Teacher</td>



                    <td>
                        <a asp-action="Details" asp-controller="kindergarden" asp-route-id="@kindergarden.Id" class="btn btn-info">Details</a>
                        <a asp-action="Update" asp-controller="kindergarden" asp-route-id="@kindergarden.Id" class="btn btn-primary">Update</a>
                        <a asp-action="Delete" asp-controller="kindergarden" asp-route-id="@kindergarden.Id" class="btn btn-danger">Delete</a>

                    </td>
                </tr>
                rowNumber += 1;
            }
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

</form>